-- Coupons become an admin decision per affiliate: the self-service section is
-- off for everyone until an admin opens it, with an optional custom ceiling on
-- the discount that affiliate may offer.
ALTER TABLE "affiliates" ADD COLUMN "couponsEnabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "affiliates" ADD COLUMN "maxCouponPercent" integer;--> statement-breakpoint

-- Every affiliate has one permanent discount code (created by the system);
-- other coupons are made by the affiliate or generated by an admin.
ALTER TABLE "affiliate_coupons" ADD COLUMN "permanent" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "affiliate_coupons" ADD COLUMN "createdBy" text;--> statement-breakpoint
CREATE UNIQUE INDEX "affiliate_coupons_permanent" ON "affiliate_coupons" USING btree ("affiliateId") WHERE "permanent";--> statement-breakpoint

-- Transactional emails: one row per email event. The unique key is what keeps
-- an event from being emailed twice; the row also carries the retry state and
-- the delivery result. Email state is separate from payout state.
CREATE TABLE "email_events" (
	"id" serial PRIMARY KEY NOT NULL,
	"key" text NOT NULL,
	"template" text NOT NULL,
	"sender" text NOT NULL,
	"recipient" text NOT NULL,
	"subject" text NOT NULL,
	"html" text NOT NULL,
	"text" text NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"lastError" text,
	"nextAttemptAt" timestamp DEFAULT now() NOT NULL,
	"affiliateId" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"sentAt" timestamp
);--> statement-breakpoint
CREATE UNIQUE INDEX "email_events_key" ON "email_events" USING btree ("key");--> statement-breakpoint
CREATE INDEX "email_events_due" ON "email_events" USING btree ("status","nextAttemptAt");--> statement-breakpoint

-- One partner account, set up at the owner's request (2026-10-02): a $1
-- minimum payout, coupons open with discounts up to 95%, and a 100% commission
-- rule. Does nothing if that account isn't an affiliate yet — the same
-- settings are on the affiliate's admin page.
UPDATE "affiliates" SET "minPayoutOverride" = 1, "couponsEnabled" = true, "maxCouponPercent" = 95, "updatedAt" = now() WHERE lower("email") = 'eslaamelsawi@gmail.com';--> statement-breakpoint
INSERT INTO "affiliate_rules" ("scope", "affiliateId", "ratePercent", "note", "createdBy")
SELECT 'affiliate', a."id", 100, 'Owner request: 100% commission', 'system'
FROM "affiliates" a
WHERE lower(a."email") = 'eslaamelsawi@gmail.com'
	AND NOT EXISTS (SELECT 1 FROM "affiliate_rules" r WHERE r."affiliateId" = a."id" AND r."scope" = 'affiliate' AND r."enabled");
