import { db } from "@/lib/db"
import { adminAuditLog } from "@/lib/db/schema"
import type { AdminContext } from "@/lib/admin/guard"

// Human-readable names for the audit log page.
export const ACTION_LABELS: Record<string, string> = {
  "user.suspend": "Suspended user",
  "user.unsuspend": "Unsuspended user",
  "user.revoke_sessions": "Signed user out everywhere",
  "user.impersonate": "Logged in as user",
  "user.impersonate_stop": "Stopped logging in as user",
  "user.set_role": "Changed admin role",
  "plan.grant": "Granted plan",
  "plan.revoke_grant": "Revoked granted plan",
  "broker.force_sync": "Forced broker sync",
  "announcement.create": "Created announcement",
  "announcement.update": "Updated announcement",
  "user.reset_2fa": "Reset two-step verification",
  "user.send_password_reset": "Sent password reset email",
  "support.reply": "Replied to support request",
  "support.status": "Changed support request status",
  "import.retry": "Retried failed import",
  "import.dismiss": "Dismissed failed import",
  "import.download": "Downloaded an imported file",
  "broker.mass_sync": "Re-synced all connections",
  "billing.refund": "Refunded a payment",
  "billing.retry_payment": "Retried a failed payment",
  "billing.pause": "Paused billing",
  "billing.resume": "Resumed billing",
  "billing.cancel": "Canceled a subscription",
  "billing.extend": "Extended a subscription",
  "billing.promo_create": "Created promo code",
  "billing.promo_delete": "Deleted promo code",
  "cases.drop_create": "Created a cases drop",
  "cases.drop_update": "Edited a cases drop",
  "cases.drop_publish": "Published a cases drop",
  "cases.drop_pause": "Paused a cases drop",
  "cases.drop_resume": "Resumed a cases drop",
  "cases.drop_end": "Ended a cases drop",
  "cases.drop_duplicate": "Duplicated a cases drop",
  "cases.drop_delete": "Deleted a cases drop",
  "cases.prize_revoke": "Revoked a prize",
  "cases.prize_redeem": "Marked a prize used",
  "templates.tag_group": "Saved starter tag group",
  "templates.tag_group_delete": "Deleted starter tag group",
  "templates.playbook": "Saved starter playbook",
  "templates.playbook_delete": "Deleted starter playbook",
  "share.disable": "Disabled a public share link",
  "affiliate.approve": "Approved an affiliate application",
  "affiliate.reject": "Rejected an affiliate application",
  "affiliate.review": "Moved an affiliate application to review",
  "affiliate.suspend": "Suspended an affiliate",
  "affiliate.reinstate": "Reinstated an affiliate",
  "affiliate.flags": "Changed an affiliate's payout hold / fraud lock",
  "affiliate.tier": "Changed an affiliate's tier",
  "affiliate.code": "Changed an affiliate's referral code",
  "affiliate.program": "Changed the affiliate program rules",
  "affiliate.tier_save": "Saved a commission tier",
  "affiliate.tier_delete": "Deleted a commission tier",
  "affiliate.rule_save": "Saved a custom commission rule",
  "affiliate.rule_toggle": "Enabled or disabled a commission rule",
  "affiliate.rule_delete": "Deleted a commission rule",
  "affiliate.adjust": "Added a ledger adjustment",
  "affiliate.commission_approve": "Approved a commission early",
  "affiliate.commission_reverse": "Reversed a commission",
  "affiliate.payout_status": "Changed a payout's status",
  "affiliate.payout_approve": "Approved a payout",
  "affiliate.payout_reject": "Rejected a payout",
  "affiliate.payout_hold": "Placed a payout on hold",
  "affiliate.payout_release": "Released a payout hold",
  "affiliate.payout_cancel": "Cancelled a payout",
  "affiliate.payout_start": "Started sending a payout",
  "affiliate.payout_mark_paid": "Marked a payout as paid",
  "affiliate.payout_fail": "Marked a payout as failed",
  "affiliate.payout_retry": "Retried a payout",
  "affiliate.payout_reverse": "Reversed a payout",
  "affiliate.payout_send_auto": "Sent a payout through the automatic sender",
  "affiliate.crypto_auto_send_on": "Switched automatic crypto sending on",
  "affiliate.crypto_auto_send_off": "Switched automatic crypto sending off",
  "affiliate.payout_transaction": "Submitted a payout transaction hash",
  "affiliate.payout_settings": "Changed payout settings",
  "affiliate.payout_pause": "PAUSED ALL PAYOUTS",
  "affiliate.payout_resume": "Resumed payouts",
  "affiliate.auto_payouts_on": "Switched automatic payouts ON",
  "affiliate.auto_payouts_off": "Switched automatic payouts OFF",
  "affiliate.auto_payouts_run": "Ran the automatic payout worker",
  "affiliate.auto_payout_enable": "Enabled automatic payouts for an affiliate",
  "affiliate.auto_payout_disable": "Disabled automatic payouts for an affiliate",
  "affiliate.payout_controls": "Changed an affiliate's payout controls",
  "affiliate.payout_method": "Changed a payout method's status",
  "affiliate.payout_method_hold": "Removed the security hold on a payout method",
  "affiliate.payout_reveal": "Viewed payout account details",
  "affiliate.signal": "Resolved a risk signal",
  "affiliate.coupon_disable": "Disabled an affiliate coupon",
  "affiliate.coupon_enable": "Enabled an affiliate coupon",
  "affiliate.coupon_access": "Changed an affiliate's coupon access",
  "affiliate.coupon_generate": "Generated a coupon for an affiliate",
  "affiliate.coupon_permanent": "Created or updated an affiliate's permanent code",
  "affiliate.resource_save": "Saved an affiliate resource",
  "affiliate.resource_delete": "Deleted an affiliate resource",
  "affiliate.announcement_save": "Saved an affiliate announcement",
  "affiliate.announcement_delete": "Deleted an affiliate announcement",
  "affiliate.export": "Exported affiliate data",
}

export async function logAdminAction(
  admin: Pick<AdminContext, "id" | "email" | "ip">,
  action: keyof typeof ACTION_LABELS,
  targetUserId: string | null,
  details?: Record<string, unknown>
) {
  await db.insert(adminAuditLog).values({
    actorId: admin.id,
    actorEmail: admin.email,
    action,
    targetUserId,
    details: details ?? null,
    ipAddress: admin.ip,
  })
}
