syntax = "proto3";

package rti;

message RequestExitPosition
{
	enum OrderPlacement {
		UNSPECIFIED = 0;
		MANUAL  = 1;
		AUTO    = 2;
	}

	int32           template_id            = 154467;
	repeated string user_msg               = 132760;
	string          window_name            = 154629;

	string          fcm_id                 = 154013;
	string          ib_id                  = 154014;
	string          account_id             = 154008;

	string          symbol                 = 110100; // optional; if set, exchange must be set too
	string          exchange               = 110101; // optional; if set, symbol must be set too
	string          trading_algorithm      = 154698;
	OrderPlacement  manual_or_auto         = 154710; // required
}
