import { randomBytes } from "node:crypto"
import { and, eq, isNotNull, sql } from "drizzle-orm"
import { db } from "@/lib/db"
import { affiliateCampaigns, affiliateCoupons, affiliates } from "@/lib/db/schema"
import { createPromoCode, deletePromoCode } from "@/lib/admin/whop"
import { getProductIdForPlan } from "@/lib/whop"
import { couponAccess, couponCodeValid, tierHasPerk } from "./engine"
import { affiliateTier, getProgram } from "./program"

// Affiliate coupons. Each is a REAL Whop promo code — the customer types it at
// checkout and Whop applies the discount — and the payment that follows carries
// the code, which is how a coupon attributes a sale (attribution.ts).
//
// Three ways a coupon comes to exist:
//   permanent  one standing code per affiliate, created by the system with the
//              program's discount once their tier includes a personal code (or
//              by an admin, for anyone). The affiliate can't disable it.
//   affiliate  made by the affiliate in the portal's Coupons section — which is
//              closed until an admin opens it for that affiliate — up to the
//              discount they are allowed (their own ceiling, else the program's).
//   admin      generated by an admin for one affiliate, with any discount.

const MAX_COUPONS = 10
const MAX_COUPONS_ADMIN = 100

export type CouponInput = { code: unknown; percent: unknown; durationMonths: unknown; plan?: unknown; campaignId?: unknown; usageLimit?: unknown; expiresAt?: unknown }

async function mintOnWhop(c: { code: string; percent: number; durationMonths: number; plan: string | null; usageLimit: number | null; expiresAt: Date | null }): Promise<string | null> {
  const promo = (await createPromoCode({
    code: c.code,
    promoType: "percentage",
    amountOff: c.percent,
    durationMonths: c.durationMonths,
    // Affiliate coupons bring in NEW customers; they aren't a discount for
    // people who already subscribe.
    newUsersOnly: true,
    onePerCustomer: true,
    stock: c.usageLimit,
    unlimitedStock: c.usageLimit == null,
    expiresAt: c.expiresAt ? c.expiresAt.toISOString() : null,
    productId: c.plan === "essential" || c.plan === "pro" ? await getProductIdForPlan(c.plan) : null,
  })) as { id?: string } | null
  return promo?.id ?? null
}

export { couponAccess }

type Terms = { percent: number; durationMonths: number; plan: string | null; usageLimit: number | null; expiresAt: Date | null }

// The parts of a coupon everyone validates the same way; the discount ceiling
// is the caller's.
function couponTerms(input: CouponInput, maxPercent: number, who: "you" | "admin"): Terms {
  const percent = Math.round(Number(input.percent))
  if (!Number.isFinite(percent) || percent < 1) throw new Error("Enter a discount percentage.")
  if (percent > maxPercent) throw new Error(who === "you" ? `The largest discount you can offer is ${maxPercent}%.` : `A discount can't be more than ${maxPercent}%.`)
  const durationMonths = Math.round(Number(input.durationMonths))
  if (!Number.isFinite(durationMonths) || durationMonths < 1 || durationMonths > 12) throw new Error("The discount can last 1 to 12 months.")
  const plan = input.plan === "essential" || input.plan === "pro" ? input.plan : null
  const usageLimit = input.usageLimit == null || input.usageLimit === "" ? null : Math.round(Number(input.usageLimit))
  if (usageLimit != null && (!Number.isFinite(usageLimit) || usageLimit < 1 || usageLimit > 100_000)) throw new Error("Enter a usage limit of at least 1, or leave it empty for no limit.")
  const expiresAt = input.expiresAt ? new Date(String(input.expiresAt)) : null
  if (expiresAt && (Number.isNaN(expiresAt.getTime()) || expiresAt.getTime() < Date.now())) throw new Error("Choose an expiry date in the future.")
  return { percent, durationMonths, plan, usageLimit, expiresAt }
}

// Reserve the code in our table first (the unique index settles a race), then
// mint it on Whop; if Whop refuses, the reservation is rolled back so a coupon
// that can't actually be redeemed never appears.
async function reserveAndMint(row: { affiliateId: number; campaignId: number | null; code: string; permanent?: boolean; createdBy: string } & Terms): Promise<{ id: number } | { taken: true }> {
  const [made] = await db
    .insert(affiliateCoupons)
    .values({ affiliateId: row.affiliateId, campaignId: row.campaignId, code: row.code, discountType: "percent", discountValue: String(row.percent), durationMonths: row.durationMonths, plan: row.plan, usageLimit: row.usageLimit, expiresAt: row.expiresAt, permanent: row.permanent ?? false, createdBy: row.createdBy })
    .onConflictDoNothing()
    .returning({ id: affiliateCoupons.id })
  if (!made) return { taken: true }
  try {
    const whopPromoId = await mintOnWhop(row)
    await db.update(affiliateCoupons).set({ whopPromoId }).where(eq(affiliateCoupons.id, made.id))
    return made
  } catch (e) {
    await db.delete(affiliateCoupons).where(eq(affiliateCoupons.id, made.id))
    throw new Error(`The coupon couldn't be created at checkout: ${e instanceof Error ? e.message : "unknown error"}`)
  }
}

export async function createCoupon(affiliateId: number, input: CouponInput): Promise<void> {
  const [program, [aff]] = await Promise.all([getProgram(), db.select({ couponsEnabled: affiliates.couponsEnabled, maxCouponPercent: affiliates.maxCouponPercent }).from(affiliates).where(eq(affiliates.id, affiliateId))])
  if (!aff) throw new Error("Affiliate account not found.")
  const access = couponAccess(aff, program)
  // Decided here, on the server: a hidden menu item is not what keeps the section closed.
  if (!program.couponsEnabled) throw new Error("Coupons aren't available in the program right now.")
  if (!access.enabled) throw new Error("Creating coupons isn't enabled for your account. Your permanent code still works — contact affiliate support if you need custom codes.")
  const code = String(input.code ?? "").trim().toUpperCase()
  if (!couponCodeValid(code)) throw new Error("Use 3–20 capital letters, numbers, dashes or underscores for the code.")
  const terms = couponTerms(input, access.maxPercent, "you")

  let campaignId: number | null = null
  if (input.campaignId != null && input.campaignId !== "") {
    const [c] = await db.select({ id: affiliateCampaigns.id }).from(affiliateCampaigns).where(and(eq(affiliateCampaigns.id, Number(input.campaignId)), eq(affiliateCampaigns.affiliateId, affiliateId)))
    if (!c) throw new Error("That campaign no longer exists.")
    campaignId = c.id
  }

  const [[count], [taken]] = await Promise.all([
    db.select({ v: sql<number>`count(*)::int` }).from(affiliateCoupons).where(and(eq(affiliateCoupons.affiliateId, affiliateId), eq(affiliateCoupons.status, "active"), eq(affiliateCoupons.permanent, false))),
    db.select({ id: affiliateCoupons.id }).from(affiliateCoupons).where(eq(affiliateCoupons.code, code)),
  ])
  if (taken) throw new Error("That code is already taken. Choose another.")
  if ((count?.v ?? 0) >= MAX_COUPONS) throw new Error(`You can have up to ${MAX_COUPONS} active coupons. Disable one first.`)

  const made = await reserveAndMint({ affiliateId, campaignId, code, createdBy: "affiliate", ...terms })
  if ("taken" in made) throw new Error("That code is already taken. Choose another.")
}

// A short code nobody has to think up: the affiliate's own code plus the
// discount, then with random letters if that is taken.
const randomSuffix = (n: number) => Array.from(randomBytes(n), (b) => "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[b % 32]).join("")
function codeCandidates(affiliateCode: string, percent: number): string[] {
  const base = affiliateCode.toUpperCase().replace(/[^A-Z0-9_-]/g, "").replace(/^[_-]+/, "").slice(0, 14) || "TL"
  return [`${base}${percent}`, `${base}${percent}${randomSuffix(2)}`, `${base}${randomSuffix(4)}`, `TL${randomSuffix(8)}`].filter(couponCodeValid)
}

// Admin: generate a coupon for one affiliate. Any discount up to 100%, with
// the code typed in or made up here. Not subject to the affiliate's own
// ceiling or to their Coupons section being open — it is the admin's coupon to give.
export async function adminCreateCoupon(affiliateId: number, input: CouponInput, adminId: string): Promise<{ code: string }> {
  const [aff] = await db.select({ id: affiliates.id, code: affiliates.code, status: affiliates.status }).from(affiliates).where(eq(affiliates.id, affiliateId))
  if (!aff) throw new Error("That affiliate no longer exists.")
  if (aff.status !== "approved") throw new Error("Coupons can be generated once the affiliate is approved.")
  const terms = couponTerms(input, 100, "admin")
  const [count] = await db.select({ v: sql<number>`count(*)::int` }).from(affiliateCoupons).where(eq(affiliateCoupons.affiliateId, affiliateId))
  if ((count?.v ?? 0) >= MAX_COUPONS_ADMIN) throw new Error(`This affiliate already has ${MAX_COUPONS_ADMIN} coupons.`)

  const typed = String(input.code ?? "").trim().toUpperCase()
  if (typed) {
    if (!couponCodeValid(typed)) throw new Error("Use 3–20 capital letters, numbers, dashes or underscores for the code.")
    const made = await reserveAndMint({ affiliateId, campaignId: null, code: typed, createdBy: adminId, ...terms })
    if ("taken" in made) throw new Error("That code is already taken. Choose another, or leave it empty to generate one.")
    return { code: typed }
  }
  let last: unknown = null
  for (const code of codeCandidates(aff.code, terms.percent)) {
    try {
      const made = await reserveAndMint({ affiliateId, campaignId: null, code, createdBy: adminId, ...terms })
      if (!("taken" in made)) return { code }
    } catch (e) {
      // e.g. the code already exists on Whop from somewhere else: try the next one
      last = e
    }
  }
  throw last instanceof Error ? last : new Error("A free code couldn't be found. Type one in instead.")
}

// --- The permanent code ----------------------------------------------------------

type CouponRow = typeof affiliateCoupons.$inferSelect

export async function permanentCoupon(affiliateId: number): Promise<CouponRow | null> {
  const [row] = await db.select().from(affiliateCoupons).where(and(eq(affiliateCoupons.affiliateId, affiliateId), eq(affiliateCoupons.permanent, true)))
  return row ?? null
}

// Makes sure an approved, set-up affiliate has their permanent code, and
// returns it. Safe to call as often as you like: the database allows one
// permanent coupon per affiliate, so two callers at once end up with the same
// one. Returns null when permanent codes are off, or the affiliate isn't ready.
//
// The personal code is a TIER PERK: it is created once the affiliate's tier
// includes it. A code that already exists is always returned — reaching for it
// never takes one away — and an admin can give one to anyone (`force`).
export async function ensurePermanentCoupon(affiliateId: number, opts: { force?: boolean } = {}): Promise<CouponRow | null> {
  const existing = await permanentCoupon(affiliateId)
  if (existing) return existing
  const program = await getProgram()
  if (!(program.permanentCouponPercent > 0)) return null
  const [aff] = await db.select({ code: affiliates.code, status: affiliates.status, onboardedAt: affiliates.onboardedAt }).from(affiliates).where(eq(affiliates.id, affiliateId))
  // The code is built from their referral code, which they choose at onboarding.
  if (!aff || aff.status !== "approved" || !aff.onboardedAt) return null
  if (!opts.force && !tierHasPerk(await affiliateTier(affiliateId), "coupon")) return null

  const base = aff.code.toUpperCase().replace(/[^A-Z0-9_-]/g, "").replace(/^[_-]+/, "").slice(0, 16)
  const candidates = [base, ...codeCandidates(aff.code, program.permanentCouponPercent)].filter(couponCodeValid)
  const terms: Terms = { percent: program.permanentCouponPercent, durationMonths: program.permanentCouponMonths, plan: null, usageLimit: null, expiresAt: null }
  let last: unknown = null
  for (const code of candidates) {
    try {
      const made = await reserveAndMint({ affiliateId, campaignId: null, code, permanent: true, createdBy: "system", ...terms })
      if (!("taken" in made)) return permanentCoupon(affiliateId)
      // Not inserted: either that code is in use, or another caller just made
      // this affiliate's permanent coupon.
      const now = await permanentCoupon(affiliateId)
      if (now) return now
    } catch (e) {
      last = e
    }
  }
  if (last) console.error("[affiliates] permanent coupon couldn't be created:", affiliateId, last instanceof Error ? last.message : last)
  return null
}

// Affiliates whose code couldn't be minted at the time get theirs — those
// whose tier includes it (the daily job does this through perks.syncAllTierPerks).
export async function ensurePermanentCoupons(limit = 50): Promise<{ created: number }> {
  const program = await getProgram()
  if (!(program.permanentCouponPercent > 0)) return { created: 0 }
  const rows = await db
    .select({ id: affiliates.id })
    .from(affiliates)
    .where(and(eq(affiliates.status, "approved"), isNotNull(affiliates.onboardedAt), sql`not exists (select 1 from ${affiliateCoupons} c where c."affiliateId" = ${affiliates.id} and c."permanent")`))
    .orderBy(affiliates.id)
    .limit(limit)
  let created = 0
  for (const r of rows) if (await ensurePermanentCoupon(r.id).catch(() => null)) created++
  return { created }
}

// Admin: put the permanent code back in line with the program's current
// discount (the promo code on Whop can't be edited, so it is replaced). The
// code itself — what the affiliate has been telling people — stays the same.
export async function refreshPermanentCoupon(affiliateId: number): Promise<CouponRow | null> {
  const existing = await permanentCoupon(affiliateId)
  // An admin asking for it gives the code whatever the affiliate's tier.
  if (!existing) return ensurePermanentCoupon(affiliateId, { force: true })
  const program = await getProgram()
  if (!(program.permanentCouponPercent > 0)) throw new Error("Permanent codes are switched off in the program rules.")
  if (existing.whopPromoId) await deletePromoCode(existing.whopPromoId).catch((e) => console.error("[affiliates] couldn't remove the promo code on Whop:", e instanceof Error ? e.message : e))
  const whopPromoId = await mintOnWhop({ code: existing.code, percent: program.permanentCouponPercent, durationMonths: program.permanentCouponMonths, plan: null, usageLimit: null, expiresAt: null })
  await db.update(affiliateCoupons).set({ discountValue: String(program.permanentCouponPercent), durationMonths: program.permanentCouponMonths, status: "active", whopPromoId }).where(eq(affiliateCoupons.id, existing.id))
  return permanentCoupon(affiliateId)
}

// --- Status ----------------------------------------------------------------------

// Disabling removes the promo code from Whop so it stops working at checkout;
// the row (and its history) stays. Enabling mints it again.
// `affiliateId` null = an admin acting; otherwise the affiliate on their own coupon.
export async function setCouponStatus(affiliateId: number | null, couponId: number, status: "active" | "disabled"): Promise<void> {
  const [c] = await db
    .select()
    .from(affiliateCoupons)
    .where(and(eq(affiliateCoupons.id, couponId), affiliateId == null ? undefined : eq(affiliateCoupons.affiliateId, affiliateId)))
  if (!c) throw new Error("That coupon no longer exists.")
  if (affiliateId != null && c.permanent) throw new Error("Your permanent code can't be switched off or on from here. Contact affiliate support.")
  if (c.status === status) return
  if (status === "disabled") {
    if (c.whopPromoId) await deletePromoCode(c.whopPromoId).catch((e) => console.error("[affiliates] couldn't remove the promo code on Whop:", e instanceof Error ? e.message : e))
    await db.update(affiliateCoupons).set({ status: "disabled", whopPromoId: null }).where(eq(affiliateCoupons.id, c.id))
    return
  }
  if (affiliateId != null) {
    const [program, [aff]] = await Promise.all([getProgram(), db.select({ couponsEnabled: affiliates.couponsEnabled, maxCouponPercent: affiliates.maxCouponPercent }).from(affiliates).where(eq(affiliates.id, affiliateId))])
    if (!aff || !couponAccess(aff, program).enabled) throw new Error("Creating coupons isn't enabled for your account.")
  }
  if (c.expiresAt && c.expiresAt.getTime() < Date.now()) throw new Error("That coupon has expired. Create a new one.")
  const left = c.usageLimit == null ? null : Math.max(0, c.usageLimit - c.uses)
  if (left === 0) throw new Error("That coupon has reached its usage limit.")
  const whopPromoId = await mintOnWhop({ code: c.code, percent: Number(c.discountValue), durationMonths: c.durationMonths, plan: c.plan, usageLimit: left, expiresAt: c.expiresAt })
  await db.update(affiliateCoupons).set({ status: "active", whopPromoId }).where(eq(affiliateCoupons.id, c.id))
}

// Admin: open or close the Coupons section for one affiliate, and set the
// largest discount they may offer (null = the program's).
export async function setCouponAccess(affiliateId: number, input: { couponsEnabled?: boolean; maxCouponPercent?: number | null }): Promise<{ userId: string; previous: Record<string, unknown>; next: Record<string, unknown> }> {
  const [aff] = await db.select().from(affiliates).where(eq(affiliates.id, affiliateId))
  if (!aff) throw new Error("That affiliate no longer exists.")
  let max = aff.maxCouponPercent
  if (input.maxCouponPercent !== undefined) {
    if (input.maxCouponPercent === null) max = null
    else {
      max = Math.round(Number(input.maxCouponPercent))
      if (!Number.isFinite(max) || max < 1 || max > 100) throw new Error("The largest discount must be between 1 and 100%, or empty to follow the program.")
    }
  }
  const next = { couponsEnabled: typeof input.couponsEnabled === "boolean" ? input.couponsEnabled : aff.couponsEnabled, maxCouponPercent: max }
  await db.update(affiliates).set({ ...next, updatedAt: new Date() }).where(eq(affiliates.id, affiliateId))
  return { userId: aff.userId, previous: { couponsEnabled: aff.couponsEnabled, maxCouponPercent: aff.maxCouponPercent }, next }
}
